[theme]
theme = "native"

[icons]
icons = "none"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

# [[block]]
# block = "disk_space"
# path = "/"
# info_type = "free"
# alert_unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0
# format = " $available.eng(w:2) "

[[block]]
block = "memory"
format = " MEM $mem_total_used_percents.eng(w:2) "

[[block]]
block = "temperature"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
