[theme]
theme = "native"

[icons]
icons = "none"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " MEM $mem_total_used_percents.eng(w:2) "

[[block]]
block = "temperature"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
format = " STO $percentage "

[[block]]
block = "backlight"
cycle = [20, 50]
format = " BRI $brightness "

[[block]]
block = "battery"

[[block]]
block = "uptime"
interval = 900

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
